### PR TITLE
fix: bump vendor/ubuntu-desktop-provision

### PR DESCRIPTION
**Pull request by sergio-costas**

### CODE REVIEW

**Comment by sergio-costas** [comment]
@kenvandine This patch updates the submodules to the last version, adding the patch for the password.

**Review by kenvandine — APPROVED** [review]
:+1:

**Comment by kenvandine** [comment]
@sergio-costas please fix the conflict, good to merge once that is done

**Comment by sergio-costas** [comment]
It seems that it was already done in master...

**Pull request closed without merging**
